language: python
python: 
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

install: 
  - pip3 install image

script: 
 - python hide.py -e "message" picture.png
